baseURL: http://example.org/
theme: FixIt

# language code ["en", "zh-CN", "fr", "pl", ...]
languageCode: en
# language name ["English", "简体中文", "Français", "Polski", ...]
languageName: English

# Author config
author:
  name: Michael
  email: "frenchmike@gmail.com"
  link: ""


# Markup related configuration in Hugo
markup:
  highlight:
    noClasses: false
