baseURL: http://example.org/
theme: FixIt

languageCode: en
languageName: English

# Author config
author:
  name: "Michael"
  email: "frenchmike@gmail.com"
  link: ""
  avatar: "/images/emoticon.png"

# Markup related configuration in Hugo
markup:
  highlight:
    noClasses: false
