# Menu config
main:
  - identifier: posts
    name: Posts
    url: /posts/
    weight: 1
  - identifier: categories
    name: "Categories"
    url: /categories/
    title: ""
    weight: 2
  - identifier: tags
    name: Tags
    url: /tags/
    weight: 3
