# site default theme ["auto", "light", "dark"]
defaultTheme: "auto"
gitRepo: ""
fingerprint: ""
dateFormat: "2006-01-02"
# website title for Open Graph and Twitter Cards
title: "My site"
# website description for RSS, SEO, Open Graph and Twitter Cards
description: "This is me Michael"
# website images for Open Graph and Twitter Cards
images: []

# Header config
header:
  desktopMode: "fixed"
  mobileMode: "auto"
  title:
    logo: "/images/emoticon.svg"
    name: ""
    typeit: false

# Footer config
footer:
  enable: true
  custom: ""
  hugo: false
  copyright: true
  author: true
  since: 2022
  icp: ""
  license: ""

# Section (all posts) page config
section:
  paginate: 20
  dateFormat: "01-02"
  rss: 10

# List (category or tag) page config
list:
  paginate: 20
  dateFormat: "01-02"
  rss: 10

# home page config
home:
  rss: 10
  profile:
    enable: true
    gravatarEmail: ""
    avatarURL: "/images/palm-trees.png"
    title: "Hey, I am Michael"
    subtitle: "Web Dev | Math | Tropics"
    typeit: true
    social: true
    disclaimer: ""
  posts:
    enable: true
    paginate: 6
    defaultHiddenFromHomePage: false

# social config
social:
  GitHub: "MSeutin"
  Linkedin: "michael-seutin-83a4aa21/"
  Twitter: "frenchmike1"
  Gitlab: "MSeutin"
  Email: "frenchmike@gmail.com"
  RSS: false
