# site default theme ["auto", "light", "dark"]
defaultTheme: "auto"
gitRepo: "MSeutin"
fingerprint: ""
dateFormat: "2006-01-02"
title: "Michael Seutin - Indie Hacker, Math Enthusiast, Explorer"
description: "Welcome to my digital space, where I explore mindset, success, math, and build web apps"
keywords: ['Web Development', 'Math', 'Michael Seutin', 'CS', 'Mindset']
images: []

# Search config
search:
  enable: true
  type: "lunr"
  contentLength: 4000
  placeholder: ""
  maxResultLength: 10
  snippetLength: 30
  highlightTag: "em"
  absoluteURL: false
  algolia:
    index: ""
    appID: ""
    searchKey: ""
  fuse:
    isCaseSensitive: false
    minMatchCharLength: 2
    findAllMatches: false
    location: 0
    threshold: 0.3
    distance: 100
    ignoreLocation: false
    useExtendedSearch: false
    ignoreFieldNorm: false


# Header config
header:
  desktopMode: "fixed"
  mobileMode: "auto"
  title:
    logo: "/images/emoticon.svg"
    name: ""
    typeit: false

# Footer config
footer:
  enable: true
  custom: ""
  hugo: false
  copyright: true
  author: true
  since: 2022
  icp: ""
  license: ""

# Section (all posts) page config
section:
  paginate: 20
  dateFormat: "01-02"
  rss: 10

# List (category or tag) page config
list:
  paginate: 20
  dateFormat: "01-02"
  rss: 10

# home page config
home:
  rss: 10
  profile:
    enable: true
    gravatarEmail: ""
    avatarURL: "/images/palm-trees.png"
    title: "Hey, I am Michael"
    subtitle: "Web Dev | Math | Tropics"
    typeit: true
    social: true
    disclaimer: ""
  posts:
    enable: true
    paginate: 6
    defaultHiddenFromHomePage: false

# social config
social:
  GitHub: "MSeutin"
  Linkedin: "michael-seutin-83a4aa21/"
  Twitter: "frenchmike1"
  Gitlab: "MSeutin"
  Email: "frenchmike@gmail.com"
  RSS: false

# github corner
githubCorner:
    enable: true
    permalink: "https://github.com/MSeutin"
    title: "View source on GitHub"
    position: "right"